version: "3"

services:
  hilfling-auth:
    networks:
      - traefik
    labels:
      - traefik.port = 8080
      - traefik.http.routers.auth-api.rule=Host("auth.fg.carosa.no")
      - traefik.http.routers.registry.service=auth-api

networks: 
  traefik:
    external: true

