version: "3"

services:
  auth-db:
    container_name: auth-db
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./postgres/sql:/postgres/sql"
    ports:
      - "5432:5432"
    labels:
      - traefik.enable = false
    environment:
      POSTGRES_DB: authdb

  hilfling-auth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: hilfling-auth
    environment:
      DEBUG: "true"
      SERVING_PORT: ":7070"
    ports:
      - "7070:7070"
    volumes:
      - .:/home/hilfling-oauth
    working_dir: /home/hilfling-oauth/src
    networks:
      - db
    command: bash -c "go mod download && make serve"

volumes:
  db-data:
