version: "3.3"

services:  
  authdb:
    container_name: authdb
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    volumes: 
      - "db-data:/var/lib/postgresql/data"
      - "./postgres/sql:/postgres/sql"
    ports:
      - "5432:5432"
    labels: 
      - traefik.enable = false
    networks: 
      - traefik
    environment: 
      POSTGRES_DB: authdb

  auth-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    container_name: auth-api
    working_dir: /home/hilfling-oauth
    environment: 
      GIN_MODE: "release"
    networks:
      - traefik
    expose: 
      - "7070"
    labels:
      - traefik.port = 7070
      - traefik.http.routers.auth-api.rule=Host("auth.fg.carosa.no")
      - traefik.http.routers.registry.service=auth-api

volumes: 
  db-data:

networks: 
  traefik:
    external: true
